name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Go First
        run: echo 'welcome to first....'
      - name: Go Second
        run: echo 'trigger second...'

